export type TokenClientId = 'juicebox' | 'skipjack' | 'suitmedia' | 'artdigital';

export type TokenClient = {
  id: TokenClientId;
  brand: string;
  legalName: string;
  remainingUsd: number;
  remainingTokens?: number;
};

export type TokenLedgerKind = 'topup' | 'usage';

export type TokenLedgerEntry = {
  date: string;
  clientId: TokenClientId;
  kind: TokenLedgerKind;
  usd: number;
  tokens?: number;
  note: string;
};

export const TOKEN_PACK_USD = 750;
export const TOKEN_PACK_TOKENS = 333_000_000;
export const TOKENS_PER_USD = TOKEN_PACK_TOKENS / TOKEN_PACK_USD;

export const TOKEN_CLIENTS: TokenClient[] = [
  {
    id: 'juicebox',
    brand: 'Juicebox',
    legalName: 'Juicebox',
    remainingUsd: 311,
    remainingTokens: 158_286_000,
  },
  {
    id: 'skipjack',
    brand: 'Skipjack',
    legalName: 'PT Iklan Kreatif Bangsa',
    remainingUsd: 186,
  },
  {
    id: 'suitmedia',
    brand: 'Suitmedia',
    legalName: 'PT Suitmedia Kreasi Indonesia',
    remainingUsd: 233,
    remainingTokens: 79_365_000,
  },
  {
    id: 'artdigital',
    brand: 'Art Digital',
    legalName: 'PT. Seni Kreasi Digital',
    remainingUsd: 186,
  },
];

export const TOKEN_CLIENT_COLOR: Record<TokenClientId, string> = {
  juicebox: '#7dd3fc',
  skipjack: '#38bdf8',
  suitmedia: '#94a3b8',
  artdigital: '#cbd5e1',
};

export const TOKEN_LEDGER: TokenLedgerEntry[] = [
  {
    date: '30 Sep 2026',
    clientId: 'juicebox',
    kind: 'topup',
    usd: 750,
    note: 'Token pack',
  },
  {
    date: '30 Sep 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 14,
    note: 'Usage',
  },
  {
    date: '30 Sep 2026',
    clientId: 'suitmedia',
    kind: 'usage',
    usd: 20,
    note: 'Usage',
  },
  {
    date: '30 Sep 2026',
    clientId: 'artdigital',
    kind: 'usage',
    usd: 20,
    note: 'Usage',
  },
  {
    date: '30 Sep 2026',
    clientId: 'suitmedia',
    kind: 'usage',
    usd: 5,
    note: 'Usage',
  },
  {
    date: '30 Sep 2026',
    clientId: 'skipjack',
    kind: 'usage',
    usd: 20,
    note: 'Usage',
  },
  {
    date: '1 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 150,
    note: 'Usage',
  },
  {
    date: '1 Oct 2026',
    clientId: 'skipjack',
    kind: 'usage',
    usd: 80,
    note: 'Usage',
  },
  {
    date: '1 Oct 2026',
    clientId: 'artdigital',
    kind: 'usage',
    usd: 80,
    note: 'Usage',
  },
  {
    date: '1 Oct 2026',
    clientId: 'suitmedia',
    kind: 'usage',
    usd: 164,
    note: 'Usage',
  },
  {
    date: '1 Oct 2026',
    clientId: 'suitmedia',
    kind: 'usage',
    usd: 13,
    note: 'Usage',
  },
  {
    date: '1 Oct 2026',
    clientId: 'suitmedia',
    kind: 'usage',
    usd: 12,
    note: 'Usage',
  },
  {
    date: '1 Oct 2026',
    clientId: 'skipjack',
    kind: 'usage',
    usd: 50,
    note: 'Usage',
  },
  {
    date: '1 Oct 2026',
    clientId: 'artdigital',
    kind: 'usage',
    usd: 50,
    note: 'Usage',
  },
  {
    date: '1 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 25,
    note: 'Usage',
  },
  {
    date: '1 Oct 2026',
    clientId: 'suitmedia',
    kind: 'topup',
    usd: 250,
    tokens: 83_250_000,
    note: 'Top-up',
  },
  {
    date: '1 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 130,
    note: 'Usage',
  },
  {
    date: '1 Oct 2026',
    clientId: 'skipjack',
    kind: 'usage',
    usd: 64,
    note: 'Usage',
  },
  {
    date: '1 Oct 2026',
    clientId: 'artdigital',
    kind: 'usage',
    usd: 64,
    note: 'Usage',
  },
  {
    date: '1 Oct 2026',
    clientId: 'suitmedia',
    kind: 'usage',
    usd: 14,
    tokens: 4_662_000,
    note: 'Usage',
  },
  {
    date: '1 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 63,
    note: 'Usage',
  },
  {
    date: '1 Oct 2026',
    clientId: 'skipjack',
    kind: 'usage',
    usd: 12,
    note: 'Usage',
  },
  {
    date: '1 Oct 2026',
    clientId: 'artdigital',
    kind: 'usage',
    usd: 12,
    note: 'Usage',
  },
  {
    date: '1 Oct 2026',
    clientId: 'suitmedia',
    kind: 'usage',
    usd: 14,
    tokens: 4_662_000,
    note: 'Usage',
  },
  {
    date: '1 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 43,
    note: 'Usage',
  },
  {
    date: '1 Oct 2026',
    clientId: 'skipjack',
    kind: 'usage',
    usd: 4,
    note: 'Usage',
  },
  {
    date: '1 Oct 2026',
    clientId: 'artdigital',
    kind: 'usage',
    usd: 4,
    note: 'Usage',
  },
  {
    date: '1 Oct 2026',
    clientId: 'suitmedia',
    kind: 'usage',
    usd: 2,
    tokens: 666_000,
    note: 'Usage',
  },
  {
    date: '1 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 15,
    note: 'Usage',
  },
  {
    date: '1 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 20,
    note: 'Usage',
  },
  {
    date: '1 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 34,
    note: 'Usage',
  },
  {
    date: '1 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 19,
    note: 'Usage',
  },
  {
    date: '1 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 38,
    note: 'Usage',
  },
  {
    date: '1 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 33,
    note: 'Usage',
  },
  {
    date: '1 Oct 2026',
    clientId: 'suitmedia',
    kind: 'usage',
    usd: 2,
    tokens: 666_000,
    note: 'Usage',
  },
  {
    date: '1 Oct 2026',
    clientId: 'skipjack',
    kind: 'usage',
    usd: 14,
    note: 'Usage',
  },
  {
    date: '1 Oct 2026',
    clientId: 'artdigital',
    kind: 'usage',
    usd: 14,
    note: 'Usage',
  },
  {
    date: '1 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 33,
    note: 'Usage',
  },
  {
    date: '1 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 42,
    note: 'Usage',
  },
  {
    date: '1 Oct 2026',
    clientId: 'skipjack',
    kind: 'usage',
    usd: 15,
    note: 'Usage',
  },
  {
    date: '1 Oct 2026',
    clientId: 'artdigital',
    kind: 'usage',
    usd: 15,
    note: 'Usage',
  },
  {
    date: '1 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 13,
    note: 'Usage',
  },
  {
    date: '1 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 13,
    note: 'Usage',
  },
  {
    date: '1 Oct 2026',
    clientId: 'juicebox',
    kind: 'topup',
    usd: 1500,
    tokens: 832_500_000,
    note: 'Top-up',
  },
  {
    date: '1 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 13,
    tokens: 7_215_000,
    note: 'Usage',
  },
  {
    date: '1 Oct 2026',
    clientId: 'skipjack',
    kind: 'usage',
    usd: 25,
    note: 'Usage',
  },
  {
    date: '1 Oct 2026',
    clientId: 'artdigital',
    kind: 'usage',
    usd: 25,
    note: 'Usage',
  },
  {
    date: '1 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 43,
    tokens: 23_865_000,
    note: 'Usage',
  },
  {
    date: '1 Oct 2026',
    clientId: 'suitmedia',
    kind: 'usage',
    usd: 34,
    tokens: 11_322_000,
    note: 'Usage',
  },
  {
    date: '1 Oct 2026',
    clientId: 'suitmedia',
    kind: 'usage',
    usd: 24,
    tokens: 7_992_000,
    note: 'Usage',
  },
  {
    date: '1 Oct 2026',
    clientId: 'suitmedia',
    kind: 'topup',
    usd: 250,
    tokens: 83_250_000,
    note: 'Top-up',
  },
  {
    date: '1 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 18,
    tokens: 9_990_000,
    note: 'Usage',
  },
  {
    date: '1 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 21,
    tokens: 11_655_000,
    note: 'Usage',
  },
  {
    date: '1 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 34,
    tokens: 18_870_000,
    note: 'Usage',
  },
  {
    date: '1 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 23,
    tokens: 12_765_000,
    note: 'Usage',
  },
  {
    date: '1 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 15,
    tokens: 8_325_000,
    note: 'Usage',
  },
  {
    date: '1 Oct 2026',
    clientId: 'suitmedia',
    kind: 'usage',
    usd: 16,
    tokens: 5_328_000,
    note: 'Usage',
  },
  {
    date: '1 Oct 2026',
    clientId: 'skipjack',
    kind: 'usage',
    usd: 20,
    note: 'Usage',
  },
  {
    date: '1 Oct 2026',
    clientId: 'artdigital',
    kind: 'usage',
    usd: 20,
    note: 'Usage',
  },
  {
    date: '1 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 32,
    tokens: 17_760_000,
    note: 'Usage',
  },
  {
    date: '1 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 29,
    tokens: 16_095_000,
    note: 'Usage',
  },
  {
    date: '1 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 23,
    tokens: 12_765_000,
    note: 'Usage',
  },
  {
    date: '1 Oct 2026',
    clientId: 'skipjack',
    kind: 'usage',
    usd: 5,
    note: 'Usage',
  },
  {
    date: '1 Oct 2026',
    clientId: 'artdigital',
    kind: 'usage',
    usd: 5,
    note: 'Usage',
  },
  {
    date: '1 Oct 2026',
    clientId: 'suitmedia',
    kind: 'usage',
    usd: 15,
    tokens: 4_995_000,
    note: 'Usage',
  },
  {
    date: '1 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 14,
    tokens: 7_770_000,
    note: 'Usage',
  },
  {
    date: '1 Oct 2026',
    clientId: 'skipjack',
    kind: 'usage',
    usd: 12,
    note: 'Usage',
  },
  {
    date: '1 Oct 2026',
    clientId: 'artdigital',
    kind: 'usage',
    usd: 12,
    note: 'Usage',
  },
  {
    date: '1 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 22,
    tokens: 12_210_000,
    note: 'Usage',
  },
  {
    date: '1 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 25,
    tokens: 13_875_000,
    note: 'Usage',
  },
  {
    date: '2 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 23,
    tokens: 12_765_000,
    note: 'Usage',
  },
  {
    date: '2 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 35,
    tokens: 19_425_000,
    note: 'Usage',
  },
  {
    date: '2 Oct 2026',
    clientId: 'skipjack',
    kind: 'usage',
    usd: 28,
    note: 'Usage',
  },
  {
    date: '2 Oct 2026',
    clientId: 'artdigital',
    kind: 'usage',
    usd: 28,
    note: 'Usage',
  },
  {
    date: '2 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 32,
    tokens: 17_760_000,
    note: 'Usage',
  },
  {
    date: '2 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 23,
    tokens: 12_765_000,
    note: 'Usage',
  },
  {
    date: '2 Oct 2026',
    clientId: 'suitmedia',
    kind: 'usage',
    usd: 13,
    tokens: 4_329_000,
    note: 'Usage',
  },
  {
    date: '2 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 21,
    tokens: 11_655_000,
    note: 'Usage',
  },
  {
    date: '2 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 19,
    tokens: 10_545_000,
    note: 'Usage',
  },
  {
    date: '2 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 33,
    tokens: 18_315_000,
    note: 'Usage',
  },
  {
    date: '2 Oct 2026',
    clientId: 'skipjack',
    kind: 'usage',
    usd: 25,
    note: 'Usage',
  },
  {
    date: '2 Oct 2026',
    clientId: 'artdigital',
    kind: 'usage',
    usd: 25,
    note: 'Usage',
  },
  {
    date: '2 Oct 2026',
    clientId: 'suitmedia',
    kind: 'usage',
    usd: 20,
    tokens: 6_660_000,
    note: 'Usage',
  },
  {
    date: '2 Oct 2026',
    clientId: 'suitmedia',
    kind: 'usage',
    usd: 22,
    tokens: 7_326_000,
    note: 'Usage',
  },
  {
    date: '2 Oct 2026',
    clientId: 'skipjack',
    kind: 'usage',
    usd: 16,
    note: 'Usage',
  },
  {
    date: '2 Oct 2026',
    clientId: 'artdigital',
    kind: 'usage',
    usd: 16,
    note: 'Usage',
  },
  {
    date: '2 Oct 2026',
    clientId: 'skipjack',
    kind: 'usage',
    usd: 12,
    note: 'Usage',
  },
  {
    date: '2 Oct 2026',
    clientId: 'artdigital',
    kind: 'usage',
    usd: 12,
    note: 'Usage',
  },
  {
    date: '2 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 23,
    tokens: 12_765_000,
    note: 'Usage',
  },
  {
    date: '2 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 23,
    tokens: 12_765_000,
    note: 'Usage',
  },
  {
    date: '2 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 18,
    tokens: 9_990_000,
    note: 'Usage',
  },
  {
    date: '2 Oct 2026',
    clientId: 'skipjack',
    kind: 'usage',
    usd: 14,
    note: 'Usage',
  },
  {
    date: '2 Oct 2026',
    clientId: 'artdigital',
    kind: 'usage',
    usd: 14,
    note: 'Usage',
  },
  {
    date: '2 Oct 2026',
    clientId: 'skipjack',
    kind: 'usage',
    usd: 12,
    note: 'Usage',
  },
  {
    date: '2 Oct 2026',
    clientId: 'artdigital',
    kind: 'usage',
    usd: 12,
    note: 'Usage',
  },
  {
    date: '2 Oct 2026',
    clientId: 'suitmedia',
    kind: 'usage',
    usd: 28,
    tokens: 9_324_000,
    note: 'Usage',
  },
  {
    date: '2 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 13,
    tokens: 7_215_000,
    note: 'Usage',
  },
  {
    date: '2 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 12,
    tokens: 6_660_000,
    note: 'Usage',
  },
  {
    date: '2 Oct 2026',
    clientId: 'skipjack',
    kind: 'usage',
    usd: 12,
    note: 'Usage',
  },
  {
    date: '2 Oct 2026',
    clientId: 'artdigital',
    kind: 'usage',
    usd: 12,
    note: 'Usage',
  },
  {
    date: '2 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 22,
    tokens: 12_210_000,
    note: 'Usage',
  },
  {
    date: '2 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 13,
    tokens: 7_215_000,
    note: 'Usage',
  },
  {
    date: '2 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 17,
    tokens: 9_435_000,
    note: 'Usage',
  },
  {
    date: '2 Oct 2026',
    clientId: 'skipjack',
    kind: 'usage',
    usd: 14,
    note: 'Usage',
  },
  {
    date: '2 Oct 2026',
    clientId: 'artdigital',
    kind: 'usage',
    usd: 14,
    note: 'Usage',
  },
  {
    date: '2 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 14,
    tokens: 7_770_000,
    note: 'Usage',
  },
  {
    date: '2 Oct 2026',
    clientId: 'skipjack',
    kind: 'usage',
    usd: 4,
    note: 'Usage',
  },
  {
    date: '2 Oct 2026',
    clientId: 'artdigital',
    kind: 'usage',
    usd: 4,
    note: 'Usage',
  },
  {
    date: '2 Oct 2026',
    clientId: 'suitmedia',
    kind: 'usage',
    usd: 8,
    tokens: 2_664_000,
    note: 'Usage',
  },
  {
    date: '3 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 23,
    tokens: 12_765_000,
    note: 'Usage',
  },
  {
    date: '3 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 12,
    tokens: 6_660_000,
    note: 'Usage',
  },
  {
    date: '3 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 18,
    tokens: 9_990_000,
    note: 'Usage',
  },
  {
    date: '3 Oct 2026',
    clientId: 'skipjack',
    kind: 'usage',
    usd: 12,
    note: 'Usage',
  },
  {
    date: '3 Oct 2026',
    clientId: 'artdigital',
    kind: 'usage',
    usd: 12,
    note: 'Usage',
  },
  {
    date: '3 Oct 2026',
    clientId: 'skipjack',
    kind: 'usage',
    usd: 18,
    note: 'Usage',
  },
  {
    date: '3 Oct 2026',
    clientId: 'artdigital',
    kind: 'usage',
    usd: 18,
    note: 'Usage',
  },
  {
    date: '3 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 33,
    tokens: 18_315_000,
    note: 'Usage',
  },
  {
    date: '3 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 12,
    tokens: 6_660_000,
    note: 'Usage',
  },
  {
    date: '3 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 11,
    tokens: 6_105_000,
    note: 'Usage',
  },
  {
    date: '3 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 12,
    tokens: 6_660_000,
    note: 'Usage',
  },
  {
    date: '3 Oct 2026',
    clientId: 'skipjack',
    kind: 'usage',
    usd: 8,
    note: 'Usage',
  },
  {
    date: '3 Oct 2026',
    clientId: 'artdigital',
    kind: 'usage',
    usd: 8,
    note: 'Usage',
  },
  {
    date: '3 Oct 2026',
    clientId: 'skipjack',
    kind: 'usage',
    usd: 6,
    note: 'Usage',
  },
  {
    date: '3 Oct 2026',
    clientId: 'artdigital',
    kind: 'usage',
    usd: 6,
    note: 'Usage',
  },
  {
    date: '3 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 12,
    tokens: 6_660_000,
    note: 'Usage',
  },
  {
    date: '3 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 11,
    tokens: 6_105_000,
    note: 'Usage',
  },
  {
    date: '3 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 12,
    tokens: 6_660_000,
    note: 'Usage',
  },
  {
    date: '3 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 11,
    tokens: 6_105_000,
    note: 'Usage',
  },
  {
    date: '3 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 7,
    tokens: 3_885_000,
    note: 'Usage',
  },
  {
    date: '3 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 19,
    tokens: 10_545_000,
    note: 'Usage',
  },
  {
    date: '3 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 7,
    tokens: 3_885_000,
    note: 'Usage',
  },
  {
    date: '3 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 5,
    tokens: 2_775_000,
    note: 'Usage',
  },
  {
    date: '3 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 11,
    tokens: 6_105_000,
    note: 'Usage',
  },
  {
    date: '3 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 12,
    tokens: 6_660_000,
    note: 'Usage',
  },
  {
    date: '3 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 7,
    tokens: 3_885_000,
    note: 'Usage',
  },
  {
    date: '3 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 2,
    tokens: 1_110_000,
    note: 'Usage',
  },
  {
    date: '3 Oct 2026',
    clientId: 'skipjack',
    kind: 'usage',
    usd: 4,
    note: 'Usage',
  },
  {
    date: '3 Oct 2026',
    clientId: 'artdigital',
    kind: 'usage',
    usd: 4,
    note: 'Usage',
  },
  {
    date: '3 Oct 2026',
    clientId: 'skipjack',
    kind: 'usage',
    usd: 8,
    note: 'Usage',
  },
  {
    date: '3 Oct 2026',
    clientId: 'artdigital',
    kind: 'usage',
    usd: 8,
    note: 'Usage',
  },
  {
    date: '3 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 19,
    tokens: 10_545_000,
    note: 'Usage',
  },
  {
    date: '3 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 12,
    tokens: 6_660_000,
    note: 'Usage',
  },
  {
    date: '3 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 13,
    tokens: 7_215_000,
    note: 'Usage',
  },
  {
    date: '3 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 3,
    tokens: 1_665_000,
    note: 'Usage',
  },
  {
    date: '3 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 12,
    tokens: 6_660_000,
    note: 'Usage',
  },
  {
    date: '3 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 8,
    tokens: 4_440_000,
    note: 'Usage',
  },
  {
    date: '3 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 12,
    tokens: 6_660_000,
    note: 'Usage',
  },
  {
    date: '3 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 8,
    tokens: 4_440_000,
    note: 'Usage',
  },
  {
    date: '3 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 12,
    tokens: 6_660_000,
    note: 'Usage',
  },
  {
    date: '3 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 7,
    tokens: 3_885_000,
    note: 'Usage',
  },
  {
    date: '3 Oct 2026',
    clientId: 'skipjack',
    kind: 'usage',
    usd: 3,
    note: 'Usage',
  },
  {
    date: '3 Oct 2026',
    clientId: 'artdigital',
    kind: 'usage',
    usd: 3,
    note: 'Usage',
  },
  {
    date: '3 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 12,
    tokens: 6_660_000,
    note: 'Usage',
  },
  {
    date: '3 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 6,
    tokens: 3_330_000,
    note: 'Usage',
  },
  {
    date: '3 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 8,
    tokens: 4_440_000,
    note: 'Usage',
  },
  {
    date: '3 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 8,
    tokens: 4_440_000,
    note: 'Usage',
  },
  {
    date: '3 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 12,
    tokens: 6_660_000,
    note: 'Usage',
  },
  {
    date: '3 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 12,
    tokens: 6_660_000,
    note: 'Usage',
  },
  {
    date: '3 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 15,
    tokens: 8_325_000,
    note: 'Usage',
  },
  {
    date: '3 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 8,
    tokens: 4_440_000,
    note: 'Usage',
  },
  {
    date: '3 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 7,
    tokens: 3_885_000,
    note: 'Usage',
  },
  {
    date: '3 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 5,
    tokens: 2_775_000,
    note: 'Usage',
  },
  {
    date: '3 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 7,
    tokens: 3_885_000,
    note: 'Usage',
  },
  {
    date: '3 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 14,
    tokens: 7_770_000,
    note: 'Usage',
  },
  {
    date: '3 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 12,
    tokens: 6_660_000,
    note: 'Usage',
  },
  {
    date: '3 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 8,
    tokens: 4_440_000,
    note: 'Usage',
  },
  {
    date: '4 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 12,
    tokens: 6_660_000,
    note: 'Usage',
  },
  {
    date: '4 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 11,
    tokens: 6_105_000,
    note: 'Usage',
  },
  {
    date: '4 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 8,
    tokens: 4_440_000,
    note: 'Usage',
  },
  {
    date: '4 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 6,
    tokens: 3_330_000,
    note: 'Usage',
  },
  {
    date: '4 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 7,
    tokens: 3_885_000,
    note: 'Usage',
  },
  {
    date: '4 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 11,
    tokens: 6_105_000,
    note: 'Usage',
  },
  {
    date: '4 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 8,
    tokens: 4_440_000,
    note: 'Usage',
  },
  {
    date: '4 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 9,
    tokens: 4_995_000,
    note: 'Usage',
  },
  {
    date: '4 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 12,
    tokens: 6_660_000,
    note: 'Usage',
  },
  {
    date: '4 Oct 2026',
    clientId: 'suitmedia',
    kind: 'usage',
    usd: 18,
    tokens: 5_994_000,
    note: 'Usage',
  },
  {
    date: '4 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 4,
    tokens: 2_220_000,
    note: 'Usage',
  },
  {
    date: '4 Oct 2026',
    clientId: 'suitmedia',
    kind: 'usage',
    usd: 11,
    tokens: 3_663_000,
    note: 'Usage',
  },
  {
    date: '4 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 8,
    tokens: 4_440_000,
    note: 'Usage',
  },
  {
    date: '4 Oct 2026',
    clientId: 'suitmedia',
    kind: 'usage',
    usd: 8,
    tokens: 2_664_000,
    note: 'Usage',
  },
  {
    date: '4 Oct 2026',
    clientId: 'juicebox',
    kind: 'usage',
    usd: 12,
    tokens: 6_660_000,
    note: 'Usage',
  },
  {
    date: '4 Oct 2026',
    clientId: 'suitmedia',
    kind: 'usage',
    usd: 16,
    tokens: 5_328_000,
    note: 'Usage',
  },
  { date: '4 Oct 2026', clientId: 'skipjack', kind: 'usage', usd: 8, note: 'Usage' },
  { date: '4 Oct 2026', clientId: 'artdigital', kind: 'usage', usd: 8, note: 'Usage' },
  { date: '4 Oct 2026', clientId: 'juicebox', kind: 'usage', usd: 8, tokens: 4_440_000, note: 'Usage' },
  { date: '4 Oct 2026', clientId: 'suitmedia', kind: 'usage', usd: 3, tokens: 999_000, note: 'Usage' },
  { date: '4 Oct 2026', clientId: 'skipjack', kind: 'usage', usd: 7, note: 'Usage' },
  { date: '4 Oct 2026', clientId: 'artdigital', kind: 'usage', usd: 7, note: 'Usage' },
  { date: '4 Oct 2026', clientId: 'juicebox', kind: 'usage', usd: 12, tokens: 6_660_000, note: 'Usage' },
  { date: '4 Oct 2026', clientId: 'suitmedia', kind: 'usage', usd: 9, tokens: 2_997_000, note: 'Usage' },
  { date: '4 Oct 2026', clientId: 'skipjack', kind: 'usage', usd: 6, note: 'Usage' },
  { date: '4 Oct 2026', clientId: 'artdigital', kind: 'usage', usd: 6, note: 'Usage' },
  { date: '4 Oct 2026', clientId: 'juicebox', kind: 'usage', usd: 6, tokens: 3_330_000, note: 'Usage' },
  { date: '4 Oct 2026', clientId: 'suitmedia', kind: 'usage', usd: 6, tokens: 1_998_000, note: 'Usage' },
  { date: '4 Oct 2026', clientId: 'juicebox', kind: 'usage', usd: 6, tokens: 3_330_000, note: 'Usage' },
  { date: '4 Oct 2026', clientId: 'juicebox', kind: 'usage', usd: 11, tokens: 6_105_000, note: 'Usage' },
  { date: '4 Oct 2026', clientId: 'juicebox', kind: 'usage', usd: 22, tokens: 12_210_000, note: 'Usage' },
  { date: '4 Oct 2026', clientId: 'juicebox', kind: 'usage', usd: 8, tokens: 4_440_000, note: 'Usage' },
  { date: '4 Oct 2026', clientId: 'juicebox', kind: 'usage', usd: 7, tokens: 3_885_000, note: 'Usage' },
];

export function usdToTokens(usd: number): number {
  return usd * TOKENS_PER_USD;
}

export function entryTokens(row: TokenLedgerEntry): number {
  return row.tokens ?? usdToTokens(row.usd);
}

export function remainingTokensFor(client: TokenClient): number {
  return client.remainingTokens ?? usdToTokens(client.remainingUsd);
}

export function usedUsdFor(clientId: TokenClientId): number {
  return TOKEN_LEDGER
    .filter((row) => row.clientId === clientId && row.kind === 'usage')
    .reduce((sum, row) => sum + row.usd, 0);
}

export function usedTokensFor(clientId: TokenClientId): number {
  return TOKEN_LEDGER
    .filter((row) => row.clientId === clientId && row.kind === 'usage')
    .reduce((sum, row) => sum + entryTokens(row), 0);
}

export function formatUsd(amount: number): string {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(amount);
}

export function formatTokens(amount: number): string {
  const millions = amount / 1_000_000;
  const rounded = Math.round(millions * 10) / 10;
  const label = Number.isInteger(rounded) ? String(rounded) : rounded.toFixed(1);
  return `${label}M`;
}
